# Generated by Django 2.1.8 on 2019-09-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=18)),
                ('user_name', models.CharField(blank=True, max_length=32, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=32, null=True)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('user_address', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
