# Generated by Django 2.1.8 on 2019-09-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=32)),
                ('article_description', models.TextField(max_length=254)),
                ('content', models.TextField()),
                ('article_public_time', models.DateField(auto_now=True)),
                ('article_picture', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=32)),
                ('author_age', models.IntegerField(blank=True, null=True)),
                ('author_gender', models.CharField(blank=True, max_length=32, null=True)),
                ('author_birthday', models.DateField(blank=True, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('author_address', models.TextField(blank=True, max_length=254, null=True)),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zero.Author'),
        ),
    ]
