# Generated by Django 2.1.8 on 2019-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zero', '0002_auto_20190915_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_description',
            field=models.TextField(),
        ),
    ]
