# Generated by Django 2.1.8 on 2019-09-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zero', '0003_auto_20190919_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_article_type',
            field=models.ManyToManyField(to='Zero.ArticleType'),
        ),
    ]
